//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationId { get; set; }
        public string LocationAddressCivicNo { get; set; }
        public string LocationAddressStreetName { get; set; }
        public string LocationAddressAppartment { get; set; }
        public string LocationAddressCity { get; set; }
        public string LocationAddressProvince { get; set; }
        public string LocationAddressPostalCode { get; set; }
        public Nullable<bool> LocationIsActive { get; set; }
    }
}
