//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Salespersons = new HashSet<Salesperson>();
        }
    
        public int LocationId { get; set; }
        public string LocationAddressCivicNo { get; set; }
        public string LocationAddressStreetName { get; set; }
        public string LocationAddressAppartment { get; set; }
        public string LocationAddressCIty { get; set; }
        public string LocationAddressProvince { get; set; }
        public string LocationAddressPostalCode { get; set; }
        public bool LocationIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salesperson> Salespersons { get; set; }
    }
}
